---
title: "Distance Decay"
output: html_document
date: "2023-06-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(betapart)
library(sf)
library(ggplot2)

load(here::here("data/specieslist_long.rda"))
load(here::here("data/qc_cand_points.rda"))
load(here::here("data/samplesize_sim.rda"))
load(here::here("data/strata_sim_points.rda"))
```


# Calculate alpha and beta diversity of sites
```{r}
specieslist_wide <- specieslist_long %>%
  mutate(abundance = 1) %>%
  pivot_wider(names_from = species, values_from = abundance, values_fill = 0) 

species_mat <- specieslist_wide %>%
  st_drop_geometry() %>%
  dplyr::select(-x, -id)

# get community distance
beta_dist <- beta.pair(species_mat, index.family = "jaccard")$beta.jac
beta_dist_df <- as_tibble(rstatix::replace_lower_triangle(as.matrix(beta_dist), by = NA)) %>%
  select(-rowname)

colnames(beta_dist_df) = specieslist_wide$id
beta_dist_df <- beta_dist_df %>%
  mutate(id = specieslist_wide$id) %>%
  pivot_longer(-id, names_to = "colid", values_to = "jaccard") %>%
  filter(!is.na(jaccard))
  

# get geographic distance, have to convert to geographic coordinate system first
geo_dist <- st_distance(qc_cand_points %>% filter(id %in% specieslist_wide$id) %>% st_transform(crs = 4326)) %>%
  units::set_units(km)
geo_dist_df <- as_tibble(rstatix::replace_lower_triangle(as.matrix(geo_dist), by = NA))

colnames(geo_dist_df) = specieslist_wide$id
geo_dist_df <- geo_dist_df %>%
  mutate(id = specieslist_wide$id) %>%
  pivot_longer(-id, names_to = "colid", values_to = "geo") %>%
  filter(!is.na(geo))

dist_df <- left_join(beta_dist_df, geo_dist_df) %>%
  mutate(geo = as.numeric(geo))

usethis::use_data(dist_df)

# dist_df %>%
#   ggplot(aes(x = jaccard, y = geo)) +
#   geom_point()

```

Let's get the plots for a couple simulations (how can we average them?)
```{r}
#first let's do one of the random samples
filter_id <- samplesize_sim %>% filter(algorithm == "srs") %>% pull(simid) %>% .[1]
inc_pts <- samplesize_sim %>% 
  filter(simid == filter_id) %>%
  pull(id)

plot_pts <- dist_df %>% 
  filter(id %in% inc_pts, colid %in% inc_pts) 


plot_pts %>%
  ggplot(aes(x = geo, y = 1 - jaccard)) +
  ylab("Jaccard similarity") +
  xlab("Distance (km)") +
  geom_point()

```
Let's try to estimate the distance decay model
```{r}
# # Get the indexes of points included in the simulation
# inc_indx <- which(specieslist_wide$id %in% inc_pts)
# 
# sub_beta_dist <- usedist::dist_subset(beta_dist, inc_indx)
# sub_geo_dist <- usedist::dist_subset(geo_dist, inc_indx)
# 
# est_mod <- decay.model(sub_beta_dist, sub_geo_dist, model.type = "exponential", y.type = "dissimilarities")
```

# For each rep, fit a glm to the decay and get a slope
```{r}
decay_glm <- function(simid, sim, selected_ids){
  sample_dist <- dist_df %>%
    filter(id %in% selected_ids, colid %in% selected_ids) 
  
  fit <- glm(1-jaccard ~ geo, data = sample_dist)
  
  broom::tidy(fit) %>% 
    filter(term == "geo") %>% 
    select(slope = estimate) %>% 
    mutate(simid = simid, sim_type = sim)
}

decay_est <- strata_sim_points %>%
  select(simid, algorithm, id, rep, sample_size) %>%
  mutate(sim_type = "stratified_equal_prob") %>%
  bind_rows(samplesize_sim %>% mutate(sim_type = "equal_prob")) %>%
  select(-x) %>%
  #filter(simid %in% unique(samplesize_sim$simid)[1:3]) %>%
  group_by(simid, sim_type) %>%
  group_map(~decay_glm(simid = unique(.x$simid), sim = unique(.x$sim_type), selected_ids = .x$id), .keep = TRUE) %>%
  bind_rows() %>%
  left_join(samplesize_sim %>% st_drop_geometry() %>% select(-id, -x) %>% distinct())

mean_decay <- decay_est %>%
  group_by(algorithm, sample_size, sim_type) %>%
  summarize(se = sd(slope), slope = mean(slope))
```

Figure
```{r}
my_pal <- c("#d9be3b", "#77976e", "#086788", "#cc8214", "#bfac88", "#99adbf")
group_colors <- c("cube" = my_pal[1], "grts" = my_pal[6], "lpm1" = my_pal[3], "lpm2" = my_pal[4], "scps" = my_pal[2], "srs" = my_pal[5])

mean_decay %>%
    select(sample_size, algorithm, slope) %>%
    filter(algorithm %in% c("cube", "grts", "lpm1", "lpm2", "scps")) %>%
    ggplot(aes(x = sample_size, y = slope, color = algorithm)) +
    facet_grid(~sim_type) +
    geom_line() +
    labs(y = "Mean decay slope", x = "sample size") +
    theme_classic() +
    #theme(legend.position = "none") +
    scale_colour_manual(values = group_colors, drop = FALSE)

ggsave(here::here("figures/distance_decay_slope.jpeg"), bg = "white")
```

