---
title: "Environmental Evaluaiton"
output: html_document
date: '2022-06-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(purrr)
library(sf)
```

Get selected points and landcover data
```{r}
load(here::here("data/env_pts_data.rda")) #environmental data for each point
load(here::here("data/samplesize_sim.rda"))
load(here::here("data/strata_sim_points.rda"))

envdata <- env_pts_data %>% 
  select(-starts_with(c("silvis", "ghmts")), -x) %>%
  drop_na()
```

### Jensen-shannon divergence of the env axes

Function to map across variables
```{r}
get_var_jsd <- function(env_data, var_name, sample_data){
  binned_data <- env_data %>% 
  select(ID, !!var_name) %>%
  mutate(bins = ggplot2::cut_interval(!!sym(var_name), n = 10, labels = FALSE)) 

total_dist <- binned_data %>% 
  count(bins) %>% 
  pivot_wider(names_from = bins, values_from = n, values_fill = 0) %>%
  mutate(temp_id = var_name)

sim_dist <- left_join(sample_data, binned_data, by = c("id" = "ID")) %>% 
  group_by(simid, sim_type) %>% 
  count(bins) %>% 
  pivot_wider(names_from = bins, values_from = n, values_fill = 0) %>%
  ungroup() %>%
  unite( col = "temp_id", simid, sim_type, sep = "-") %>% 
  bind_rows(total_dist)
  
jsd <- philentropy::JSD(as.matrix(select(sim_dist, -temp_id)), est.prob = "empirical") %>%
  as_tibble() %>%
  bind_cols(sim_dist$temp_id, .)

colnames(jsd) <- c("temp_id", sim_dist$temp_id)

comp_total <- select(jsd, temp_id, !!sym(var_name)) %>%
  filter(temp_id != var_name) %>%
  separate(temp_id, into = c("simid", "sim_type"), sep = "-")
}

#get_var_jsd(envdata, "chelsa.climbio10_1981")
```

Get JSD for all variables 
```{r}
comb_sim_df <- strata_sim_points %>%
  select(colnames(samplesize_sim)) %>%
  mutate(sim_type = "stratified_equal_prob") %>%
  bind_rows(samplesize_sim %>% mutate(sim_type = "equal_prob"))

env_vars <- envdata %>% select(-ID) %>% colnames()

#plan("multisession", workers = length(env_vars))
# env_vars_jsd <- map(env_vars[c(1, 4, 20, 21, 22)], ~get_var_jsd(env_data = envdata, var_name = .x, sample_data = comb_sim_df)) #%>% 
  # reduce(full_join, by = "simid") 
rm(ecoreg_pts, ecoregion_inc_prob, ecoregion_points_data, env_pts_data, 
   qc_cand_points, samplesize_sim, strata_sim, strata_sim_points)

env_vars_jsd <- purrr::map(env_vars, ~get_var_jsd(env_data = envdata, var_name = .x, sample_data = comb_sim_df)) %>% 
  purrr::reduce(full_join, by = c("simid", "sim_type"))

usethis::use_data(env_vars_jsd)
```

Final df structure
```{r}
jsd_df <- env_vars_jsd %>%
  tidyr::separate(simid, "_", into = c("rep", "sample_size", "algorithm_type", "aux")) %>%
  tidyr::unite("algorithm", algorithm_type, aux, sep = "_", na.rm = TRUE) %>% 
  mutate(across(-c(algorithm, sim_type), ~as.numeric(.))) %>%
  group_by(sample_size, algorithm, sim_type) %>%
  summarize(across(-rep, ~mean(sqrt(.x))), .groups = "keep") %>% #take the square root so we actually have JSDistance (not divergence)
  ungroup() %>%
  pivot_longer(c(everything(), -sample_size, -algorithm, -sim_type), names_to = "env_variable") %>%
  group_by(sample_size, algorithm, sim_type) %>%
  summarize(jsd = mean(value), .groups = "keep") %>%
  ungroup()

usethis::use_data(jsd_df)
```
