---
title: "Spatial Balance"
output: html_document
date: '2022-05-27'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(sf)
library(survey)
library(spsurvey)
library(BalancedSampling)
library(ggplot2)
library(sampling)
library(purrr)
#library(raster)

#devtools::load_all()
```

```{r}
load(here::here("data/qc_cand_points.rda"))
load(here::here("data/ecoregion_inc_prob.rda"))
load(here::here("data/samplesize_sim.rda"))
load(here::here("data/strata_sim_points.rda"))
```


Get spatial balance metric for each rep
```{r}
# use the `Spbsampling` function
dist_mat <- as.matrix(dist(qc_cand_points %>% 
                             arrange(id) %>%
                             dplyr::mutate(lon = sf::st_coordinates(.)[,1], 
                                           lat = sf::st_coordinates(.)[,2]) %>%
                             as_tibble() %>%
                             select(-x)))

# This calculates inclusion probabilities and spatial balance metric for an equal probability study design
sb_eqprob <- samplesize_sim %>%
  #filter(simid %in% c("1_10_srs","1_10_grts","1_10_cube","1_10_scps","1_10_lpm1","1_10_lpm2")) %>%
  group_by(simid) %>%
  group_map(~{
    n <- unique(.x$sample_size)
    N <- dim(dist_mat)[1]
    pik <- rep(n/N,N)
    
    id_vec <- unique(.x$id)
    
    .x %>%
      select(algorithm, sample_size, rep) %>% 
      distinct() %>%
      mutate(sb = Spbsampling::sbi(dist_mat, pik, id_vec))
  }) %>%
  bind_rows() %>%
  unite("simid", rep, sample_size, algorithm, remove = FALSE)

usethis::use_data(sb_eqprob)

# sb_eqprob %>%
#   group_by(sample_size, algorithm) %>%
#   summarize(mean = mean(sb), sd = sd(sb)) %>%
#   ggplot(aes(x = sample_size, y = mean, color = algorithm)) +
#   geom_line() +
#   labs(y ="Mean Sample Balance", x = "Sample Size") 
# geom_ribbon(aes(ymin = mean - sd, ymax = mean + sd))
```

Let's do stratified equal probability
```{r}
# the inclusion probabilities df still excludes some points, let's fill in the holes
ecoregion_inc_prob_fill <- ecoregion_inc_prob %>%
  select(sample_size, id, inc_prob)

sb_strat_df <- strata_sim_points %>%
  #filter(simid %in% c("1_10_srs","1_10_grts","1_10_cube","1_10_scps","1_10_lpm1","1_10_lpm2")) %>%
  group_by(simid) %>%
  group_map(~{
    
    n <- unique(.x$sample_size)
    N <- dim(dist_mat)[1]
    
    samp_size_data <- ecoregion_inc_prob %>%
      filter(sample_size == n)
    
    #get missing id's from inc_prob data
    missing_id <- tibble(id = setdiff(1:N, samp_size_data$id), inc_prob = 0)
    
    pik <- bind_rows(samp_size_data, missing_id) %>%
      arrange(id) %>%
      pull(inc_prob)
    
    id_vec <- unique(.x$id)
    
    .x %>%
      select(algorithm, sample_size, rep) %>% 
      distinct() %>%
      mutate(sb = Spbsampling::sbi(dist_mat, pik, id_vec))
  }) %>%
  bind_rows() %>%
  unite("simid", rep, sample_size, algorithm, remove = FALSE)

usethis::use_data(sb_strat_df)

# sb_strat_df %>%
#   group_by(sample_size, algorithm) %>%
#   summarize(mean = mean(sb), sd = sd(sb)) %>%
#   ggplot(aes(x = sample_size, y = mean, color = algorithm)) +
#   geom_line() +
#   labs(y ="Mean Sample Balance", x = "Sample Size") +
#   geom_ribbon(aes(ymin = mean - sd, ymax = mean + sd))
```

Final dataframe
```{r}
sb_df <- sb_eqprob %>%
  mutate(sim_type = "equal_prob") %>%
  bind_rows(sb_strat_df %>% mutate(sim_type = "stratified_equal_prob")) %>%
  group_by(sample_size, algorithm, sim_type) %>%
  summarize(sp = mean(sb), .groups = "keep") 

usethis::use_data(sb_df)
```

