---
title: "Visualization"
output: html_document
date: "2022-09-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(cowplot)
```

Load dataframes of mean evaluation metrics
```{r}
load(here::here("data/sb_df.rda")) #spatial balance metrics
load(here::here("data/iucn_df.rda")) #iucn range map coverage (mean richness)
load(here::here("data/jsd_df.rda")) #jensen-shannon divergence averaged across environmental variables

#load(here::here("data/qc_mammals.rda"))
#n_distinct(qc_mammals$binomial)
# results in 61 total mammals in Quebec

metrics <- full_join(iucn_df, sb_df) %>%
  full_join(jsd_df) %>%
  # we want all of the metrics between 0 and 1 and decaying 
  mutate(iucn_scale = 1 - (iucn/61), # fraction of species missing
         sb_scale = as.vector(scale(sb,center=min(sb),scale=diff(range(sb)))),
         jsd_scale = as.vector(scale(jsd,center=min(jsd),scale=diff(range(jsd))))) %>%
  tidyr::separate_wider_delim(algorithm, delim = "_", names = c("algorithm", "pt1", "pt2"), too_few = "align_start") %>%
  mutate(stratified = sim_type == "stratified_equal_prob",
         aux_vars = case_when(
           pt1 == "aux" ~ TRUE, 
           pt2 == "aux" ~ TRUE,
           .default = FALSE
         ),
         inclusion_prob = case_when(pt1 == "uneq" ~ "unequal", 
                                    .default = "equal"),
         algorithm_name = case_when(
           algorithm %in% c("lpm1", "lpm2", "scps") & inclusion_prob == "unequal" ~ paste(algorithm, "unequal"),
           .default = algorithm
         )) %>%
  select(-c(sim_type, pt1, pt2)) 

metric_exc <- metrics %>%
  tidyr::unite(sim_type, algorithm_name, stratified, remove = FALSE) %>%
  filter(!sim_type %in% c("lpm1_TRUE", "lpm2_TRUE", "scps_TRUE")) %>%
  select(-sim_type)
```
Function to plot a panel
```{r}
plot_metric_curves <- function(data, metric_var, type, ylabel, xlabel, aux, exclude_algos = NULL, color_list, plot_path = NULL, ...){
  plot_data <- data %>%
    select(sample_size, algorithm, stratified, !!metric_var, aux_vars) %>%
    filter(stratified == type, aux_vars == aux)
    
  if (aux == TRUE){
    plot_data <- plot_data %>%
      bind_rows(data %>% 
                  filter(algorithm == "srs", stratified == type) %>% 
                  select(sample_size, algorithm, stratified, !!metric_var, aux_vars))
  }
  
  plot <- plot_data %>% 
    ggplot(aes(x = sample_size, y = !!sym(metric_var), color = algorithm)) +
    geom_line(position = position_dodge(width = 0.002)) +
    labs(y = ylabel, x = xlabel) +
    theme_classic() +
    theme(legend.position = "none", ...) +
    scale_colour_manual(values = color_list, drop = FALSE)
  
  # if(metric_var == "sb_scale"){
  #   plot <- plot + ylim(0,0.007)
  #   } else if (metric_var == "jsd_scale"){
  #   plot <- plot + ylim(0, 0.75)
  #   }else{
  #   plot <- plot + ylim(0, 0.3)
  # }

  if(hasArg(plot_path)) ggsave(plot_path, plot = plot)
  
  return(plot)
}

#my_pal <- NatParksPalettes::natparks.pals(name="DeathValley",n=6,type="discrete")

# Set palette colors and assign to algorithms
pal <- khroma::color("light")(9)

#my_pal <- c("#d9be3b", "#77976e", "#086788", "#cc8214", "#bfac88", "#99adbf")
# algo_colors <- c("cube" = pal[1], "grts" = pal[6], "lpm1" = pal[3], "lpm2" = pal[4], "scps" = pal[2], "srs" = "black",
#                  "lpm1 unequal" = pal[5], "lpm2 unequal" = pal[7] , "scps unequal" = pal[8])
algo_colors <- c("cube" = pal[1], "grts" = pal[2], "lpm2" = pal[3], "scps" = pal[4], "srs" = "black",
                 "lpm2 unequal" = pal[5] , "scps unequal" = pal[6])

# plot_df <- tibble(#metric_var = c("iucn_scale", "iucn_scale", "sb_scale", "sb_scale", "jsd_scale", "jsd_scale"),
#   metric_var = c("iucn_scale", "iucn_scale", "sb", "sb", "jsd", "jsd"),
#                   type = rep(c("equal_prob", "stratified_equal_prob"), 3),
#                   ylabel = c("Percent IUCN Species Missing", "", "Mean Spatial Balance", "", "Mean Divergence", ""),
#                   xlabel = c("", "", "", "", "Sample Size", "Sample Size"),
#                   #exclude_algos = list("", "", "", list("lpm1", "lpm2", "scps"), "", "")
#                   exclude_algos = list("", "", "", "", "", "")
#                  )
```

Plot for no auxiliary variables 
```{r}
noaux_plot_df <- tibble(#metric_var = c("iucn_scale", "iucn_scale", "sb", "sb", "jsd_scale", "jsd_scale"),
  metric_var = c("iucn_scale", "iucn_scale", "sb_scale", "sb_scale", "jsd_scale", "jsd_scale"),
                  type = rep(c(FALSE, TRUE), 3),
                  ylabel = c("Percent IUCN Species Missing", "", "Mean Spatial Balance", "", "Mean Divergence", ""),
                  xlabel = c("", "", "", "", "Sample Size", "Sample Size")
                  )

noaux_plot_list <- purrr::pmap(noaux_plot_df, plot_metric_curves, data = metric_exc, aux = FALSE, color_list = algo_colors, axis.title = element_text(size=7))

noaux_plot_join <- plot_grid(plotlist=noaux_plot_list, labels = "AUTO", nrow = 3, align = 'vh',
                       hjust = -1, axis = "l", scale = 0.85)

## Get fiddly bits for the grid plot ##

# legend first
# legend_plot <- metrics %>%
#     filter(sim_type == "equal_prob") %>%
#     ggplot(aes(x = sample_size, y = iucn, color = algorithm)) +
#     geom_line() +
#     theme_classic() +
#     theme(axis.title = element_text(size=7)) +
#   scale_colour_manual(values = group_colors, drop = FALSE)

legend_plot <- metric_exc %>%
    filter(aux_vars == FALSE) %>%
    ggplot(aes(x = sample_size, y = iucn, color = algorithm)) +
    geom_line() +
    theme_classic() +
    theme(axis.title = element_text(size=7)) +
  scale_colour_manual(values = algo_colors, drop = TRUE, name = "algorithm")

legend <- get_legend(legend_plot)

# titles for columns
col_title1 <- ggdraw() + 
  draw_label(
    "Equal Probability",
    fontface = 'bold',
    x = 0,
    hjust = -1
  )

col_title2 <- ggdraw() + 
  draw_label(
    "Stratified",
    fontface = 'bold',
    x = 0,
    hjust = -1.6
  )

# put it all together
col_title_row <- plot_grid(col_title1, col_title2, ncol = 2)
noaux <- plot_grid(noaux_plot_join, legend, rel_widths = c(3,.4)) %>%
  plot_grid(col_title_row, .,ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1))

ggsave(here::here("figures/sim_evaluation_noaux.jpeg"), plot = noaux, bg = "white", height = 11, width = 11)
```

Plot for simulations with auxiliary variables
```{r}
aux_plot_df <- tibble(metric_var = c("iucn_scale", "iucn_scale", "sb_scale", "sb_scale", "jsd_scale", "jsd_scale"),
                  type = rep(c(FALSE, TRUE), 3),
                  ylabel = c("Percent IUCN Species Missing", "", "Mean Spatial Balance", "", "Mean Divergence", ""),
                  xlabel = c("", "", "", "", "Sample Size", "Sample Size")
                  )

aux_plot_list <- purrr::pmap(aux_plot_df, plot_metric_curves, data = metric_exc, aux = TRUE, color_list = algo_colors, axis.title = element_text(size=7))

aux_plot_join <- plot_grid(plotlist=aux_plot_list, labels = "AUTO", nrow = 3, align = 'vh',
                       hjust = -1, axis = "l", scale = 0.85)

## Get fiddly bits for the grid plot ##

legend_plot <- metrics %>%
  filter(aux_vars == TRUE | algorithm == "srs") %>%
    ggplot(aes(x = sample_size, y = iucn, color = algorithm_name)) +
    geom_line() +
    theme_classic() +
    theme(axis.title = element_text(size=7)) +
  scale_colour_manual(values = algo_colors, drop = TRUE, name = "algorithm")

legend <- get_legend(legend_plot)

# titles for columns
col_title1 <- ggdraw() + 
  draw_label(
    "Equal Probability",
    fontface = 'bold',
    x = 0,
    hjust = -1
  )

col_title2 <- ggdraw() + 
  draw_label(
    "Stratified",
    fontface = 'bold',
    x = 0,
    hjust = -1.6
  )

# put it all together
col_title_row <- plot_grid(col_title1, col_title2, ncol = 2)
aux <- plot_grid(aux_plot_join, legend, rel_widths = c(3,.4)) %>%
  plot_grid(col_title_row, .,ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1))

ggsave(here::here("figures/sim_evaluation_aux.jpeg"), plot = aux, bg = "white", height = 11, width = 11)
```
Plot comparing different stratification implementations
```{r}
strat_data <- metrics %>% filter(algorithm_name %in% c("lpm2", "scps", "lpm2 unequal", "scps unequal"),
                                                                                        stratified == TRUE) %>%
                                 select(-algorithm) %>%
                                 mutate(algorithm = case_when(
                                   algorithm_name == "lpm2" ~ "LPM naive",
                                   algorithm_name == "scps" ~ "SCPS naive",
                                   algorithm_name == "lpm2 unequal" ~ "LPM unequal",
                                   algorithm_name == "scps unequal" ~ "SCPS unequal"))

strat_palette <-  c("LPM naive" = pal[1], "LPM unequal" = pal[2], "SCPS naive" = pal[4], "SCPS unequal" = pal[3], "srs" = "black")

strat_comp_df <- tibble(metric_var = c("iucn_scale", "sb_scale", "jsd_scale"),
                  type = rep(TRUE, 3),
                  ylabel = c("Percent IUCN Species Missing", "Mean Spatial Balance", "Mean Divergence"),
                  xlabel = c("", "", "Sample Size")
                  )

strat_plot_list <- purrr::pmap(strat_comp_df, plot_metric_curves, data = strat_data, 
                             aux = TRUE, color_list = strat_palette, axis.title = element_text(size=7))

strat_plot_join <- plot_grid(plotlist=strat_plot_list, labels = "AUTO", nrow = 3, align = 'vh',
                       hjust = -1, axis = "l", scale = 0.85)

legend_plot <- strat_data %>%
  filter(aux_vars == TRUE | algorithm == "srs") %>%
    ggplot(aes(x = sample_size, y = iucn, color = algorithm)) +
    geom_line() +
    theme_classic() +
    theme(axis.title = element_text(size=7)) +
  scale_colour_manual(values = strat_palette, drop = TRUE, name = "algorithm")

legend <- get_legend(legend_plot)

# put it all together
strat <- plot_grid(strat_plot_join, legend, rel_widths = c(3,.4)) %>%
  plot_grid(.,ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1))

ggsave(here::here("figures/strat_comparison.jpeg"), plot = strat, bg = "white", height = 11, width = 6)
```


Save plots individually with all axis labels 
```{r}
# paths <- c("iucn_eq.jpeg", "iucn_strat.jpeg", "sb_eq.jpeg", "sb_strat.jpeg", "jsd_eq.jpeg", "jsd_strat.jpeg")
# indv_plot_df <- tibble(metric_var = c("iucn_scale", "iucn_scale", "sb_scale", "sb_scale", "jsd_scale", "jsd_scale"),
#                   type = rep(c("equal_prob", "stratified_equal_prob"), 3),
#                   ylabel = c("Percent IUCN Species Missing", "Percent IUCN Species Missing", 
#                              "Mean Spatial Balance", "Mean Spatial Balance", "Mean Divergence", "Mean Divergence"),
#                   xlabel = rep("Sample Size", 6),
#                   plot_path = here::here("figures", paths)
#                   )
# 
# purrr::pmap(indv_plot_df, plot_metric_curves, data = metrics, 
#             color_list = group_colors, axis.title = element_text(size=15), axis.text=element_text(size=10))
```
Quick figure for mean species per site
```{r}
load(here::here("data/mean_species_site.rda"))

mean_species_site %>%
    select(sample_size, algorithm, sim_type, mean_site_species) %>%
    ggplot(aes(x = sample_size, y = mean_site_species, color = algorithm)) +
    facet_grid(~sim_type) +
    geom_line() +
    labs(y = "mean species per site", x = "sample size") +
    theme_classic() +
    #theme(legend.position = "none") +
    scale_colour_manual(values = group_colors, drop = FALSE)
```

